USE ANALYSTS;

-- TO CHECK THE NUMBER OF ROWS
SELECT COUNT(*) AS TOTAL_ROWS FROM JOBS;

-- FILTERED THE ANALYSTS TITLE
CREATE TABLE ANALYST_JOBS AS
SELECT * FROM JOBS 
WHERE TITLE LIKE "%ANALYST%";

-- CREATING TABLE FOR SKILLS AS FORMAT IS BAD
CREATE TABLE JOB_SKILLS AS 
SELECT TITLE,COMPANY,SKILL FROM (
SELECT  TITLE, COMPANY,SKILL_1 AS SKILL FROM ANALYST_JOBS
UNION ALL
SELECT  TITLE, COMPANY,SKILL_2 AS SKILL FROM  ANALYST_JOBS
UNION ALL
SELECT  TITLE, COMPANY,SKILL_3 AS SKILL FROM  ANALYST_JOBS
UNION ALL
SELECT  TITLE, COMPANY,SKILL_4 AS SKILL FROM  ANALYST_JOBS
UNION ALL
SELECT  TITLE, COMPANY,SKILL_5 AS SKILL FROM  ANALYST_JOBS
UNION ALL
SELECT  TITLE, COMPANY,SKILL_6 AS SKILL FROM  ANALYST_JOBS
UNION ALL
SELECT  TITLE, COMPANY,SKILL_7 AS SKILL FROM  ANALYST_JOBS
UNION ALL
SELECT  TITLE, COMPANY,SKILL_8 AS SKILL FROM  ANALYST_JOBS
)T
WHERE SKILL IS NOT NULL
AND SKILL<> ' ';

SELECT * FROM JOB_SKILLS;
-- TOTAL NO OF ROWS IN JOB_SKILLS
SELECT COUNT(*) AS TOTAL_ROWS FROM JOB_SKILLS;

-- TOP SKILLS ANALYSIS
SELECT SKILL,COUNT(*) AS DEMAND 
FROM JOB_SKILLS 
GROUP BY SKILL ORDER BY DEMAND DESC;